language: java
deploy:
  provider: heroku
  api_key:
    secure: Tk2QT8HOku/agNoMUk8exnp4fBrNCnOqbo0poGnUcNnyOW9jfYxCAD/L7jF1JIGjfo05fs9ITsblS4t2h0xszi0viV8XaPpZnpaokbA9JfVANs3ROMuwuEl0Z/g7zIgsPzINOUjrqmYkSssFvSuyswptL+cLlxAAikpa9n+hYL22E8zGhOSYJ4sHnA2rjNxuKoUZD6tqMbZ5h1CLzxgfD9aVwOlHsEuAWyQSeuhG87Wg+y3MXoZvgbtEU7DJUy/TQtXto+KcRTeLLcmzZpp3bZlcniZx+5BH6BcwF1xcH/rTFVA+kDIZDGCaC9D72jh50W7H3YHu3cLY3RX4YcXOTilZzpGOKMhUr6ea+XnG65zWDxwfdwBlw2p/A5KvAk9+n4UhI84vIQ25VA02+qf7l21GMlpqJKhYa9mslbMW7iw2xuN3GjlgwJYYDaJA+wbYJSHRpsBgGYlqH4aouyXjhOZgcEnxPens5BGv6OxWUhVh4FMQjovexUawQXU7+K1HuLmqUNkXGisy0lkjT1EleB4/mHdlBcWO97toxGZD8huxzYqJcEB0PBxQixE4S2wTMoNOA3JOEckAWT3+lji6EMjQT9zQEUa4Y6wfvRVwdmEYaHKX5+7uM5XptMUA1F8OCrMgZkxUJJpWQUKfZGJSH/hZ7cA80yuA2TsBelSbOLs=
  app: pik-app
